### ISSUE TITLE
Fine Tuning 

### ISSUE THREAD

**Issue by moh3th1** [Azure/ObjectDetectionUsingCntk#1]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by PatrickBue** [comment]
The tutorial uses an AlexNet model which was pre-trained on millions of images. Hence it is fine if you only have a small amount of annotated data. Just follow part 1 of the tutorial - that uses a small toy dataset but nevertheless learns an OK classifier.
