### ISSUE TITLE
Error in 1_computeRois.py

### ISSUE THREAD

**Issue by Al3x68** [Azure/ObjectDetectionUsingCntk#10]
Hi, I am trying to follow the tutorial but when executing the first script 1_computeRois.py I get an error stating that there is no module named 'past'. 
I installed the required modules from the Prerequisites section and installed future as well after having a look on the internet. Unfortunately without success.
Here is the full error message : 

1_computeRois.py
Traceback (most recent call last):
  File "C:\Users\alexi\Documents\Work\AgileBI\ObjectDetectionUsingCntk-master\1_computeRois.py", line 3, in <module>
    import PARAMETERS
  File "C:\Users\alexi\Documents\Work\AgileBI\ObjectDetectionUsingCntk-master\PARAMETERS.py", line 2, in <module>
    from helpers import *
  File "C:\Users\alexi\Documents\Work\AgileBI\ObjectDetectionUsingCntk-master\helpers.py", line 6, in <module>
    from past.utils import old_div
ImportError: No module named 'past'

Any help would be greatly appreciated.

**Comment by PatrickBue** [comment]
Hi Alex, to verify: did you install all the requirements using the pip.exe install -r requirements.txt command? That installs the 'future' package among others.
Are you using CNTK's [script-driven installation](https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script)? If so, make sure to activate the CNTK environment before the installation (cntkpy35.bat), and also when trying to run the scripts.

**Comment by Al3x68** [comment]
Hi Patrick, thank you for your reply.
I installed the prerequisites and activated the CNTK environment (I was able to run the tutorials).
Today I deleted the python and CNTK environment and now it is working, it was probably a mistake I did during the installation. Sorry about that and thank you again for your time, this looks awesome I'm impatient to try it.
Cheers, Alex

**Comment by PatrickBue** [comment]
No problem at all. Glad it's working now!

**Comment by Mohannvell** [comment]
I have installed cntk25-py35 and I get the same error. Which version of CNTK to be preferred?
