### ISSUE TITLE
imgPath hardcoded in 6_scoreImage.py

### ISSUE THREAD

**Issue by Al3x68** [Azure/ObjectDetectionUsingCntk#11]
Hi, I ran into an error while running the script 6_scoreImage.py.
The problem is that the imgPath is hard-coded at the beginning of the script. 
I managed to make the variable imgPath dynamic using the imgDir from PARAMETERS,py.

imgPath = imgDir + "testImages\WIN_20160803_11_48_26_Pro.jpg"

I will submit a pull request for the change.
Thank you again for this amazing presentation.
Cheers, Alex

Here is the full previous error message :
python 6_scoreImage.py
--------------------------------------------------------------
2017-04-11 12:26:37
PARAMETERS: datasetName = grocery
Loading DNN..
Time loading DNN [ms]: 731.994
Loading svm weights..
Time loading svm [ms]: 137.04
ERROR: image path does not exist.
Traceback (most recent call last):
  File "6_scoreImage.py", line 46, in <module>
    imgOrig = imread(imgPath)
  File "C:\local\ObjectDetectionUsingCntk\helpers.py", line 774, in imread
    error
NameError: name 'error' is not defined

**Comment by PatrickBue** [comment]
See discussion here: https://github.com/Azure/ObjectDetectionUsingCntk/issues/13
