### ISSUE TITLE
Script A1_annotateImages.py not working

### ISSUE THREAD

**Issue by Al3x68** [Azure/ObjectDetectionUsingCntk#13]
Hello,
When executing the script A1_annotateImages.py, after a short moment the script finishes with the message done without having had the chance to annotates the images, is that normal?

In the parameters I changed the imagesToAnnotateDir parameter to my local directory which contains the folders "negative", "positive" and "testImages" (and the pictures).

It seems that the collection imgFilenames is not populated properly, but I really have no experience with Python and all I have been trying to do has not solved the problem.

Am I missing something here? (Maybe I have to execute other scripts before this one?)

Thank you for your support!
Cheers, Alex

**Comment by PatrickBue** [comment]
Hi Alex,
You have to change imagesToAnnotateDir to point directly to the folder where the images are, and not to the folder which contains the "negative", "positive" and "testImages" sub-directories. It should work then. You need to annotate the positive images and the test images.

**Comment by ppXD** [comment]
test

**Comment by ppXD** [comment]
test

**Comment by Al3x68** [comment]
Hi Patrick,
Thank you for your feedback.
I think it would be feasible using a second for loop and iterating over the subFolders parameter, but for now it's working using the path name directly.
