### ISSUE TITLE
Running on Azure DSVM ubuntu 

### ISSUE THREAD

**Issue by pamio** [Azure/ObjectDetectionUsingCntk#14]
Hi, 
I followed your instructions on windows and worked fine but I can't seem to be able to get this working on azure DSVm ubuntu machine. It looks like I have permission issues installing the dependencies like dlib, easyDict etc. Any ideas on this ? 

Also, Can I use a model thats trained on windows, running on ubuntu ? Like for deploying this as a web service using azure ML ? If not, how should I go about deploying the model ? 

Thanks

**Comment by PatrickBue** [comment]
Hi, I have never tried running the code on Linux/Ubuntu. In theory it should work, but might be that the dlib or easyDict libraries are windows-only.
As for training on windows and deploying on Ubuntu (or vice versa), never tried this either, but again, I don't think there is anything in CNTK which would stop you from doing this. There might be small changes required to the code (such as not using easyDict if it is not supported in Ubuntu systems)

**Comment by AkshayAgarwal007** [comment]
@pamio Why not use a Azure DSVM Windows machine?

**Comment by pamio** [comment]
@PatrickBue Thanks for the reply. It looks like azure DSVM doesn't allow me to install libraries so I ended up using windows Azure DSVM. However, Deploying it in the traditional way seems very difficult on windows. I used apache along with wsgi mod to get this deployed, but this looks like a lot more trouble than on linux machines. I'm now using flask for api services which loads up the model and able to get the results locally, but when I try out pointing a public IP thats assigned on the DSVM, it never reaches the server. I have deployed 10s of apps on linux, but first time on windows, so may be I'm missing something. 

One more question, In order for the deployment to work, I would need to load up the model which could be found in your script no. 6, looks like that can't be used as standalone script. When I run the script, it also searches for files in proc folder which to me shouldnt be needed as the model is already copied in a different folder and the references were removed or changed.  So to cut it short, what other files/folder do I need to have it deployed as a web service ? 

@AkshayAgarwal007 Yes I'm using that for now. But not going to give on running/deploying on ubuntu. 

Thanks

**Comment by PatrickBue** [comment]
Hi,
As for the web-server:
I once had a local web-server running on my windows DSVM and set it up such that it can be called from any public web-browser. I had to do (a subset possibly) of these steps:
- Add an inbound security rule in the azure portal (network security group), to unblock the port you would like to use. Possibly deactivate the full firewall (for debugging only)
- Changed the IP address in my flask code from localhost to 0.0.0.0
- Used cherrypy (though this might not be necessary)
Hope this helps!

**Comment by PatrickBue** [comment]
And script 6_ is indeed pretty much stand alone. Changing the paths of the DNN model and/or to the SVM should be enough to run this without any other files (except as the actual code it imports).

**Comment by pamio** [comment]
Thanks @PatrickBue for your reply, 
I did exactly what you mentioned, opened the port, changed the IP address but in vain. 
One of the issues I face is that, when I use apache and WSGI, I call up the driver code, which takes a long time to load, probably because my conda env is not activated. 

Questions: 
1. Apache + WSGI -> how do I activate the conda env (cntkpy35.bat on cmd) in wsgi script. I kinda think it should be like activating a virtualenv but when I call `cntkpy35.bat` in a python script, it doesn't work.  
2. Running flask standalone works fine without issues but getting it work with wsgi, can't seem to figure out. To run flask I first call the cntkpy35.bat file and then cd into the web app dir and run the flask server. But don't know how to do it with apache. 
3. How to retrain model with new images, like updating the already trained model than training the entire model again the old and new images. 
4. Will the CPU trained model work on GPU ? I have availed a subscription on azure (all thanks your wonderful tutorial). Initially I wanted to try out CNTK, now when I think CNTK is what I want, I want to use the already trained model to server result faster, for which I think GPU instances are needed. Can I use the same model or do I have to train the model again on GPU ?

Best,
Pramod Solanky

**Comment by PatrickBue** [comment]
Hi, I'm afraid I cannot help with your Apache based questions. As for CPU trained models, yes, these should run on GPU (and vice versa). As an fyi, GPU is mostly needed for training, since they provide very high batch throughput, for scoring often CPU is fast enough (given also the over-head from the web-call itself, etc)

**Comment by pamio** [comment]
Thanks for the help

**Comment by pamio** [comment]
I was finally able to host the model through apache and wsgi on apache. Thanks :)

**Comment by PatrickBue** [comment]
that's great! glad to hear
