### ISSUE TITLE
How can i get a message (true-false) if img.jpg have labels?

### ISSUE THREAD

**Issue by fct-edilberto** [Azure/ObjectDetectionUsingCntk#15]
in 6_scoreImage i like to obtain a message true/false if the image have any label or not because i have a lot of images

```
if something:
    print('TRUE')
else:
    print('FALSE')

```

**Comment by mwangimorris** [comment]
def checkLabels(imagesToAnnotateDir):
     #loop over all images
      imgFilenames = getFilesInDirectory(imagesToAnnotateDir, ".jpg")
      for imgIndex, imgFilename in enumerate(imgFilenames):
           labelsPath = os.path.join(imagesToAnnotateDir , imgFilename[:-4] + ".bboxes.labels.tsv")
           if os.path.exists(labelsPath):
               return True //and go to other images with no labels
     return False
