### ISSUE TITLE
cuDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by MikeWise2718** [Azure/ObjectDetectionUsingCntk#2]
I go this error message when running this. I suspect this might be an out-of-memory error as I have a rather small GPU unit (only 2 GB) but I do wish the error message was more informative. Not the fault of this software or CNTK though seems to be CUDA's fault. Googling yielded no answer either - but I did find more than a few people asking about the message, some thinking it might have been memory issues.

In any case the work around is to add a `deviceId=-1` parameter to force a CPU-only invocation of CNTK to line 24 of `3_runCntk.py` like this:

     cmdStr += " deviceID=-1 ImageH={} ImageW={}".format(cntk_padHeight, cntk_padWidth)

CNTK then ran in 188 seconds on my i7-4770T CPU (not the fastest either) - and this is fine for getting the demo to work.

It would be worth having this as a flag.

**Comment by PatrickBue** [comment]
Hi, yeah, looks like this is indeed caused by the GPU running out of memory. The ResNet model is pretty memory hungry.
Glad you found a workaround.
