### ISSUE TITLE
Issue with output of NN classifier

### ISSUE THREAD

**Issue by AkshayAgarwal007** [Azure/ObjectDetectionUsingCntk#6]
The mAP in case of NN classifier seems to be very low when I tried it out.

![nn_issue](https://cloud.githubusercontent.com/assets/8170214/22342998/70710184-e41c-11e6-9ee8-e8371b43d622.PNG)

The output on the five test images looks something like this:

![nn_0win_20160803_11_28_42_pro](https://cloud.githubusercontent.com/assets/8170214/22343415/01cff85a-e41e-11e6-8216-57d197405c58.jpg)![nn_1win_20160803_11_42_36_pro](https://cloud.githubusercontent.com/assets/8170214/22343416/0209c45e-e41e-11e6-9b15-f9de27117dee.jpg)![nn_2win_20160803_11_46_03_pro](https://cloud.githubusercontent.com/assets/8170214/22343417/02303f12-e41e-11e6-85d5-289a5ea8fd41.jpg)
![nn_3win_20160803_11_48_26_pro](https://cloud.githubusercontent.com/assets/8170214/22343418/0231f5c8-e41e-11e6-8764-3502de8745b0.jpg)![nn_4win_20160803_12_37_07_pro](https://cloud.githubusercontent.com/assets/8170214/22343419/02370270-e41e-11e6-897a-44a5c0599956.jpg)

**Comment by AkshayAgarwal007** [comment]
I tried the entire process twice and it is yielding the same result.

**Comment by PatrickBue** [comment]
This is a very small dataset, and hence just training a SVM on the output of the NN is expected to work better. You could try tweaking the parameters (esp. the learning rate) for the NN training to see how much the accuracy improves.
